# Generated by cpp11: do not edit by hand

svglite_ <- function(file, bg, width, height, pointsize, standalone, aliases, id){
  .Call("_svglite_svglite_" , file, bg, width, height, pointsize, standalone, aliases, id)
}

svgstring_ <- function(env, bg, width, height, pointsize, standalone, aliases, id){
  .Call("_svglite_svgstring_" , env, bg, width, height, pointsize, standalone, aliases, id)
}

get_svg_content <- function(p){
  .Call("_svglite_get_svg_content" , p)
}


