# Generated by cpp11: do not edit by hand

svglite_ <- function(file, bg, width, height, pointsize, standalone, aliases, webfonts, id, fix_text_size) {
  .Call("_svglite_svglite_", file, bg, width, height, pointsize, standalone, aliases, webfonts, id, fix_text_size)
}

svgstring_ <- function(env, bg, width, height, pointsize, standalone, aliases, webfonts, id, fix_text_size) {
  .Call("_svglite_svgstring_", env, bg, width, height, pointsize, standalone, aliases, webfonts, id, fix_text_size)
}

get_svg_content <- function(p) {
  .Call("_svglite_get_svg_content", p)
}
