# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

svglite_ <- function(file, bg, width, height, pointsize, standalone) {
    .Call('svglite_svglite_', PACKAGE = 'svglite', file, bg, width, height, pointsize, standalone)
}

svgstring_ <- function(env, bg, width, height, pointsize, standalone) {
    .Call('svglite_svgstring_', PACKAGE = 'svglite', env, bg, width, height, pointsize, standalone)
}

