# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

devSVG_ <- function(file, bg_, width, height, pointsize, standalone) {
    .Call('svglite_devSVG_', PACKAGE = 'svglite', file, bg_, width, height, pointsize, standalone)
}

